version: '3.9'

services:
  gcloud:
    image: google/cloud-sdk:367.0.0
    volumes:
      - gcp-creds:/creds
      - .:/todo
    working_dir: /todo
    environment:
      - CLOUDSDK_CONFIG=/creds

volumes:
  gcp-creds: