name: Docker Image CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Docker-build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    
    env:
      SECRET_KEY: ${{secrets.SECRET_KEY}}
      DEBUG: ${{secrets.DEBUG}}
      DB_HOST: ${{secrets.DB_HOST}}
      DB_NAME: ${{secrets.DB_NAME}}
      DB_USER: ${{secrets.DB_USER}}
      DB_PASS: ${{secrets.DB_PASS}}
      POSTGRES_DB: ${{secrets.POSTGRES_DB}}
      POSTGRES_USER: ${{secrets.POSTGRES_USER}}
      POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker-compose -f docker-compose.yml build
      
    - name: Start the Docker image
      run: docker-compose -f docker-compose.yml up -d
      
    - name: Test and Lint
      run: docker-compose run --rm todo sh -c "flake8"

    - name: Stop containers
      if: always()
      run: docker-compose -f "docker-compose.yml" down
      
      
